-- AlterTable
ALTER TABLE "tracking_events" ADD COLUMN IF NOT EXISTS "platform" VARCHAR(50);

-- AlterTable
ALTER TABLE "stats" ADD COLUMN IF NOT EXISTS "favorites" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "stats" ADD COLUMN IF NOT EXISTS "calendar" BIGINT NOT NULL DEFAULT 0;
